### ISSUE TITLE
Support for re-mock if a mock exists

### ISSUE THREAD

**Issue by jonathannaguin** [dwyl/aws-sdk-mock#23] opened 2016-04-12 16:53 UTC
Hi,

We are facing some issues when running multiple tests with Mocha in conjunction with aws-sdk-mock.
If we run the following test JS individually with Mocha they work perfectly, but when run together, the second test run fails.

TestA is like:
```
var awsMock = require('aws-sdk-mock');

describe('Suite A', function ()
{
    before(function () {
        awsMock.mock('DynamoDB.DocumentClient', 'query', function (params, callback) {
               ...
        } 
   }
   it("Test case A", function() {
   ....
   });   
}
```

TestB is really similar:

```
var awsMock = require('aws-sdk-mock');

describe('Suite B', function ()
{
    before(function () {
        awsMock.mock('DynamoDB.DocumentClient', 'query', function (params, callback) {
               ...
        } 
   }
   it("Test case B", function() {
   ....
   });   
}
```

I added some debugging and it seems that the mocking method called in the second test belongs to the first test.
This might be because Mocha runs all the specs together in a single command, loading all the modules into a single test environment.
I am not sure if we can't change the Mocha behaviour, so the solution I am proposing is adding maybe a new method that would allow us to re-mock a method. 

Thanks!

**Comment by mkjois** [comment] 2016-04-13 03:37
You should be able to restore the mock in an `after` block for every suite. Re-mocking works fine after restoration.

```
describe('Suite A', function() {
    after(function() {
        awsMock.restore('DynamoDB.DocumentClient');
    });
});
```

**Comment by jonathannaguin** [comment] 2016-04-13 08:11
@mkjois Unfortunately, doing a `restore` does not help, still the first mocked method is being called. I have also tried a global restore instead of specifying the service, same results.

**Comment by jonathannaguin** [comment] 2016-04-13 18:07
A small test that shows the issue:

```
var test = require('tape');
var awsMock = require('../index.js');
var AWS = require('aws-sdk');

test('mock function should have been re-mocked', function(st) {

    awsMock.mock('DynamoDB.DocumentClient', 'query', function(params, callback) {
        callback(null, {
            Items: []
        });
    });

    var docClient = new AWS.DynamoDB.DocumentClient();

    awsMock.restore('DynamoDB.DocumentClient');

    awsMock.mock('DynamoDB.DocumentClient', 'query', function(params, callback) {
        callback(null, {
            Items: ["second"]
        });
    });

    docClient.query(null, function(err, data) {
        if (err) {
            console.log(err);
            st.notOk("shoud not have failed");
        } else {
            console.log("DATA: " + JSON.stringify(data));
            st.same(data, {
                Items: ["second"]
            });
        }

        st.end();
    });
});
```

**Comment by nelsonic** [comment] 2016-04-13 18:32
@nikhilaravi / @jackcarlisle thoughts?

**Comment by mkjois** [comment] 2016-04-14 08:40
In your test, `docClient`'s prototype chain connects it to the first mock because that's when it was instantiated. If you were to instantiate another AWS service after the second mock, it would work.

I believe this is the intended behavior (feature, not flaw), someone correct me if I'm wrong.

**Comment by jonathannaguin** [comment] 2016-04-14 12:52
@mkjois That did the trick! I had to adapt my code to not reuse Dynamodb clients instances, I hope it won't affect the performance. Now I have the tests working! Thanks!

**Comment by jruts** [comment] 2016-05-14 11:36
@jonathannaguin I am happy your proble; is solved!

Closing this issue since it was a ussage issue rather then the ability of the mocking library.

**Closed by jruts** 2016-05-14 11:36 UTC
Labels: enhancement, help wanted

**Comment by manojlds** [comment] 2016-11-21 12:35
> I hope it won't affect the performance

Any opinions on this?

**Comment by deanpeterson** [comment] 2017-09-05 04:28
@jonathannaguin, can you show an example of how you forced a new Dynamodb client instance after each test?
