### ISSUE TITLE
AWS.restore() throwing an error

### ISSUE THREAD

**Issue by bpedagandham** [dwyl/aws-sdk-mock#28] opened 2016-05-23 23:41 UTC
not sure if it's Sinon version issue or something else.

TypeError: Cannot read property 'restore' of undefined
    at restoreMethod (C:\Projects\xxx\node_modules\aws-sdk-mock\index.js:158:45)
    at restoreAllMethods (C:\Projects\xxx\node_modules\aws-sdk-mock\index.js:149:5)
    at restoreService (C:\Projects\xxx\node_modules\aws-sdk-mock\index.js:139:3)
    at restoreAllServices (C:\Projects\xxx\node_modules\aws-sdk-mock\index.js:131:5)
    at Object.AWS.restore (C:\Projects\xxx\node_modules\aws-sdk-mock\index.js:116:5)
    at Suite.<anonymous> (C:\Projects\xxx\test\test.spec.js:18:9)
    at context.describe.context.context (C:\Projects\xxx\node_modules\mocha\lib\interfaces\bdd.js:47:10)
    at Object.<anonymous> (C:\Projects\xxx\test\test.spec.js:2:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Projects\xxx\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Projects\xxx\node_modules\mocha\lib\mocha.js:216:14)
    at Mocha.run (C:\Projects\xxx\node_modules\mocha\lib\mocha.js:468:10)
    at Object.<anonymous> (C:\Projects\xxx\node_modules\mocha\bin\_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by jruts** [comment] 2016-05-25 22:33
@bpedagandham can you please provide your test code to see if we can pinpoint the issue?

**Comment by adnanmateenpk** [comment] 2016-05-26 22:18
having the same issue opened node console
and tried the commands
                var AWS = require('aws-sdk-mock');

		AWS.mock('DynamoDB', 'scan', function (params, callback){
		  callback(null, "successfully get items from database");
		});
		AWS.restore('DynamoDB');
this throws a similar error in console

**Comment by adnanmateenpk** [comment] 2016-05-26 22:51
my test file is like this

'use strict';
// tests for first
// Generated by serverless-mocha-plugin

const mod         = require('../functions/first/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

wrapper.init(mod);

describe('first', () => {
	beforeEach(function(){
		var AWS = require('aws-sdk-mock');

		AWS.mock('DynamoDB', 'scan', function (params, callback){
		  callback(null, "successfully get items from database");
		});
		AWS.restore('DynamoDB');
	});
	it('checks the response', (done) => {
	    wrapper.run({}, (err, response) => {
	    	expect(response).to.equal('test')
	      done();
	    });
	});
});

**Comment by adnanmateenpk** [comment] 2016-05-26 22:55
I was console.logged through your index.js and i found that on line# 158, 
`services[service].methodMocks[method].stub.restore();`
`services[service].methodMocks[method]`
this object doesnt have any 'stub' as its child

**Comment by adnanmateenpk** [comment] 2016-05-26 23:06
i have a feeling i am not using it as it should be used

**Comment by jruts** [comment] 2016-05-27 15:38
@adnanmateenpk can you put the AWS.restore in an `afterEach` function.

**Comment by adnanmateenpk** [comment] 2016-05-27 16:11
yeah i figured it out, my mistake... thanks nonetheless

________________________________

**Comment by jruts** [comment] 2016-05-30 18:05
Closing this issue due to not a bug but a usage error.

**Closed by jruts** 2016-05-30 18:05 UTC
